### ISSUE TITLE
Problem with semicolons after upgrade to v0.1.11

### ISSUE THREAD

**Issue by jonatanpedersen** [elgs/dns-zonefile#13]
Hello elgs,

Great module!

However, after upgrading to v.0.1.11 (possibly from 0.1.8, but might be wrong) we have an issue where the parser removes the last character before a semicolon.

tst 300 IN A 101.228.10.127;this is a comment

The IP in the object then becomes
101.228.10.12 instead of 101.228.10.127

Cheers,
Jonatan

**Comment by elgs** [comment]
@jonatanpedersen thank you for letting me know that. I will look at it now and get back to you soon.

**Comment by elgs** [comment]
@jonatanpedersen I confirmed this is a bug and it was introduced from 0.1.11. I will do some test with it now and hopefully a new version will be released soon.

**Comment by jonatanpedersen** [comment]
Great! thanks @elgs

**Comment by elgs** [comment]
@jonatanpedersen I have released a new version of code which should have fixed this porblem. I also have published it in both `npm` and `bower`. Would you please get the new code and let me know if it works or not. Thanks.

**Comment by jonatanpedersen** [comment]
@elgs I can confirm that the new code fixes this issue. Thanks :)
