### ISSUE TITLE
Using JSON.stringify for output of binary program

### ISSUE THREAD

**Issue by h4cc** [elgs/dns-zonefile#15]
Thanks for this programm.
I had some problems with the output of it, because what i got was something like JSON but not parseable by other languages.

Example:

```bash
$ zonefile current.zone 
{ '$ttl': '86400',
  soa: 
   { name: '@',
     minimum: 86400,
     expire: 604800,
     retry: 1800,
     refresh: 14400,
     serial: 2013103100,
     rname: 'postmaster.robot.first-ns.de.',
     mname: 'ns1.first-ns.de.' },
  ns: 
   [ { name: '@', host: 'ns1.first-ns.de.' },
     { name: '@', host: 'robotns2.second-ns.de.' },
     { name: '@', host: 'robotns3.second-ns.com.' } ],
  a: 
   [ { name: '@', ip: '1.2.3.4' },
     { name: 'localhost', ip: '127.0.0.1' },
     { name: 'mail', ip: '1.2.3.4' },
     { name: 'www', ip: '1.2.3.4' } ],
  cname: 
   [ { name: 'ftp', alias: 'www' },
     { name: 'imap', alias: 'www' },
     { name: 'loopback', alias: 'localhost' },
     { name: 'pop', alias: 'www' },
     { name: 'relay', alias: 'www' },
     { name: 'smtp', alias: 'www' } ],
  mx: [ { name: '@', preference: 10, host: 'mail' } ] }
```

But when using `JSON.stringify` before `console.log`, the output because useable JSON:

```javascript
output = JSON.stringify(output);
console.log(output);
```

The unformatted output after that will become:

```bash
$ zonefile current.zone 
{"$ttl":"86400","soa":{"name":"@","minimum":86400,"expire":604800,"retry":1800,"refresh":14400,"serial":2013103100,"rname":"postmaster.robot.first-ns.de.","mname":"ns1.first-ns.de."},"ns":[{"name":"@","host":"ns1.first-ns.de."},{"name":"@","host":"robotns2.second-ns.de."},{"name":"@","host":"robotns3.second-ns.com."}],"a":[{"name":"@","ip":"1.2.3.4"},{"name":"localhost","ip":"127.0.0.1"},{"name":"mail","ip":"1.2.3.4"},{"name":"www","ip":"1.2.3.4"}],"cname":[{"name":"ftp","alias":"www"},{"name":"imap","alias":"www"},{"name":"loopback","alias":"localhost"},{"name":"pop","alias":"www"},{"name":"relay","alias":"www"},{"name":"smtp","alias":"www"}],"mx":[{"name":"@","preference":10,"host":"mail"}]}
```

**Comment by elgs** [comment]
@h4cc sorry for a late reply. So is that a problem? Or did I not fully understand what you meant.

From what I understood, the behavior seems to be expected. The thing you got like JSON but not parseable by other languages is a javascript object, which is quite like JSON, but it's actually not. You get JSON by passing the javascript object into JSON.stringify as argument.

So please let me know if I still missed anything.

**Comment by h4cc** [comment]
No problem. Let me elaborate some more:
I was expecting a tool that will simply convert zonefiles to JSON. The only tool in my pipeline using nodejs is your "dns-zonefile". If the output would be full JSON, there would be no problem.

Maybe we could add a parameter making the output "real" JSON?

**Comment by elgs** [comment]
The purpose of the parse function is to convert a zone file to an javascript object so that it's easier for javascript code to work with the zone file data. It's pretty straightforward to turn a javascript object into JSON string using `JSON.stringify`. Therefore, I don't think it's necessary to add it to the library.

**Comment by h4cc** [comment]
I am using the binary file `bin/zonefile` only, and not the library code in `lib`. I do not have javascript code anywhere else. So there are the following problems for me, and anybody else trying to use your programm:

- The binary file should output JSON, which it does not.
- The README is showing real JSON like `"soa": { "mname": "NS1.NAMESERVER.NET.", }`, which is not the real output of your programm.
- Not everybody is using a javascript toolchain, so that converting this "not real JSON" to "real JSON" is _not_ a easy thing.

I am trying to tell you, that your binary file does not output correct JSON. And opposed to your point of view, this is a issue because currently that "JSON" can not be parsed outside of JavaScript tools.

To resolve that issue for me, i will have to use a patched `bin/zonefile` that is using `JSON.stringify`, so that my other tools (PHP, Python, ...) can work with it.

Please try to provide valid JSON, so that other people can use your tool and work.

**Comment by elgs** [comment]
Aha! I got it. Thanks @h4cc. I will investigate it and get back to you soon.

**Comment by elgs** [comment]
I have fixed this problem. npm, bower are updated. The `zonefile` command tool outputs JSON in compact mode. If you want pretty output, you may use `jq`, like this:
`zonefile -p my_zonefile.conf | jq .`

Here is the link to `jq` https://stedolan.github.io/jq/.

**Comment by h4cc** [comment]
Thanks!
