### ISSUE TITLE
Parser Captures Too Early

### ISSUE THREAD

**Issue by bryanculver** [elgs/dns-zonefile#16]
Because of the order of testing, SPF records can be interpreted as A records.

Example:

**db.example.com**
```
;
; example.com
$TTL  604800
@ IN  SOA ns1.example.com. dns.example.com. (
			2015040102			; Serial
       			604800			; Refresh
			 86400			; Retry
			   2419200			; Expire
			604800 )	; Negative Cache TTL
;
; NAME SERVERS
@			IN	NS	ns1.example.com.

;
; SPF RECORDS
@			IN	SPF	"v=spf1 a mx ~all"
```

**Demo Script**
```
var zf = require('dns-zonefile');
const fs = require('fs');
var text = fs.readFileSync('./db.example.com', 'utf8');
var input = zf.parse(text);
console.log(input)
```

**Output**
```
{ '$ttl': '604800',
  soa:
   { name: '@',
     minimum: 604800,
     expire: 2419200,
     retry: 86400,
     refresh: 604800,
     serial: 2015040102,
     rname: 'dns.example.com.',
     mname: 'ns1.example.com.' },
  ns: [ { name: '@', host: 'ns1.example.com.' } ],
  a: [ { name: '@', ip: '~all"' } ] }
```

**Comment by elgs** [comment]
Thanks @bryanculver I will look at it and get back to you soon.

**Comment by elgs** [comment]
@bryanculver I confirm it's a bug. I will try to fix it now and get back to you soon.

**Comment by bryanculver** [comment]
@elgs I have just submitted a proposed fix. Thanks for the speedy response!

**Comment by elgs** [comment]
@bryanculver thanks for the proposed fix. I have read it and understood it. It looks like this bug potentially affects all records. Now I'm trying to split the record taking the quoted string as a whole. So that anything inside the quotes will not matter.

**Comment by bryanculver** [comment]
No problem, that would probably be a better solution but I wasn't going to propose a significant rewrite.

**Comment by elgs** [comment]
Thanks @bryanculver. Give me half an hour or so. I'm rewriting most of the parser code now. Thanks for your pull requests. You uncovered some horrible problems in my code. Thank you.

**Comment by elgs** [comment]
@bryanculver I have fixed the parser bugs, hopefully. Would you please try again with the latest version of code and let me know if it works for you. Thanks.

**Comment by bryanculver** [comment]
It's generating them without quotes, which per [RFC4408](https://www.ietf.org/rfc/rfc4408.txt) section 3.1.1 it should be quoted.

**Input**
```
{ '$ttl': '604800',
  soa:
   { name: '@',
     minimum: 604800,
     expire: 2419200,
     retry: 86400,
     refresh: 604800,
     serial: 2015040102,
     rname: 'dns.example.com.',
     mname: 'ns1.example.com.' },
  ns: [ { name: '@', host: 'ns1.example.com.' } ],
  spf: [ { name: '@', data: 'v=spf1 a mx ~all' } ] }
```

**Output**
```
; SPF Records
@	IN	SPF	v=spf1 a mx ~all
```

**Comment by bryanculver** [comment]
Also I discovered a shorthand it was missing permitting. [RFC1035](http://tools.ietf.org/html/rfc1035) section 5.1:

> The following entries are defined:
> \<blank\>\[\<comment\>\]
> ...
> If an entry for an RR begins with a blank, then the RR is assumed to be owned by the last stated owner.

**Input**
```
;
; example.com
$TTL  604800
@ IN  SOA ns1.example.com. dns.example.com. (
            2015040102          ; Serial
                604800          ; Refresh
             86400          ; Retry
               2419200          ; Expire
            604800 )    ; Negative Cache TTL
;
; NAME SERVERS
@           IN  NS  ns1.example.com.

;
; A RECORDS
subdomain           IN  A  1.1.1.1
           IN  A  2.2.2.2
```

**Output**
```
{ '$ttl': '604800',
  soa:
   { name: '@',
     minimum: 604800,
     expire: 2419200,
     retry: 86400,
     refresh: 604800,
     serial: 2015040102,
     rname: 'dns.example.com.',
     mname: 'ns1.example.com.' },
  ns: [ { name: '@', host: 'ns1.example.com.' } ],
  a:
   [ { name: 'subdomain', ip: '1.1.1.1' },
     { name: 'IN', ip: '2.2.2.2' } ] }
```

I understand maintaining this association would be very difficult exporting or complicate the data structure, so possibly being extra verbose on the import would solve this issue. It just won't ever export in the shorthand format.

**Comment by elgs** [comment]
I confirm the missing quotes problem. Will have a new release soon.

**Comment by elgs** [comment]
@bryanculver both missing quotes and shorthand problem are fixed. It should parse shorthands correctly, but it will always generate full format. Would you please help to test if it works for you? Thanks.

**Comment by bryanculver** [comment]
@elgs All problems seem to be resolved on my end. Thank you very much for the quick response!

**Comment by elgs** [comment]
@bryanculver I appreciate your effort not only for finding these bugs, but also for the fix proposals. Now looking back the code before this update, it was nearly not usable at all. Thank you so much.
