### ISSUE TITLE
SyntaxError: Unexpected token [

### ISSUE THREAD

**Issue by adnanmueller** [elgs/dns-zonefile#21]
I just installed dns-zonefile on a fresh install of ubuntu 16.04 and fresh install of node and npm. Running `zonefile -p name.txt > name.json` results in the following error.

/usr/local/lib/node_modules/dns-zonefile/lib/zonefile.js:85
        for (let [key, value] in data) {
                 ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/dns-zonefile/bin/zonefile:7:20
    at Object.<anonymous> (/usr/local/lib/node_modules/dns-zonefile/bin/zonefile:53:3)
    at Module._compile (module.js:410:26)

**Comment by elgs** [comment]
Can you please share the `name.txt` which produces the same problem?

**Comment by adnanmueller** [comment]
so this is an example of the txt file

;
;  Database file (null) for work.test.com.au zone.
;      Zone version:  1524
;

;
;  Zone records
;

@                       A	220.9.12.9
test-cbr                A	220.9.12.9

**Comment by adnanmueller** [comment]
[work.test.com.au.txt](https://github.com/elgs/dns-zonefile/files/688889/work.test.com.au.txt)

**Comment by elgs** [comment]
It seems I got the output like this:

$ zonefile -p work.test.com.au.txt 
{"a":[{"name":"@","ip":"220.9.12.9"},{"name":"test-cbr","ip":"220.9.12.9"}]}

**Comment by adnanmueller** [comment]
Is there any particular version of node or npm that needs to be used?

**Comment by elgs** [comment]
Aha! I see. I guess it's because in the most recent versions, I upgraded the syntax to ES6. Do you have a chance to upgrade your Nodejs to be latest? Otherwise you can use an older version of dns-zonefile (0.1.x).

**Comment by adnanmueller** [comment]
That looks like it has solved it, manually updating node to v7.4 fixed the issue.
