### ISSUE TITLE
CAA records

### ISSUE THREAD

**Issue by ad-m** [elgs/dns-zonefile#33]
RFC 6844 published at January 2013 defined new type of DNS record: ```DNS Certification Authority Authorization (CAA) Resource Record```

The popularity of CAA is raising ( https://en.wikipedia.org/wiki/DNS_Certification_Authority_Authorization#Background ).

For this reason, it would be useful to add support also for this type of records in ```dns-zonefile```.

**Comment by elgs** [comment]
Thanks for the link! I will get myself educated about it. Meantime, if you could a chance to have a pull request, it will be greatly appreciated.

**Comment by ad-m** [comment]
Close by #35
