### ISSUE TITLE
No DS Record Type

### ISSUE THREAD

**Issue by anoncam** [elgs/dns-zonefile#40]
https://github.com/elgs/dns-zonefile/blob/fdb82e625f9569362f8837e61107a497b04b37ec/lib/zonefile.js#L1

Currently, no DS record type exists to support DNSSEC for delegated zones.

**Comment by anoncam** [comment]
See the RFC: https://tools.ietf.org/html/rfc3658

**Comment by elgs** [comment]
I apologize for the late reply. Give me some time to educate myself about the DS records.

**Comment by elgs** [comment]
@anoncam I just released 0.2.10. It should support DS records now.

**Comment by anoncam** [comment]
> @anoncam I just released 0.2.10. It should support DS records now.

Amazing!  I'd love to work with you to expand this a bit further for CAA records and some more niche record types.

We have automated quite a bit of DNS via GitOps and this tool has been a staple in our pipelines.

**Comment by anoncam** [comment]
@shebashio

**Comment by anoncam** [comment]
Resolved by [0.2.10](https://github.com/elgs/dns-zonefile/tree/0.2.10)
