### ISSUE TITLE
System tests are timing out after updating to v.0.2.7

### ISSUE THREAD

**Issue by sofisl** [elgs/dns-zonefile#41]
As the title says, our system tests seem to keep failing after updating: https://github.com/googleapis/nodejs-dns/pull/469

We even tried further increasing the timeout to no avail:
https://github.com/googleapis/nodejs-dns/pull/463

I tried to check in the release notes, but there was no guidance on the updating process. 

Do you have any recommendations for how to upgrade this dependency?

For reference, this is the particular test that keeps timing out: https://github.com/googleapis/nodejs-dns/blob/f27204da7203cbef3e8d7315dcd1abf83b5affbe/system-test/dns.ts#L179

**Comment by elgs** [comment]
Interesting. Having lunch now. I will check it when I get back to my computer.

**Comment by elgs** [comment]
I found the error message in your test looks like this:
```
1) dns
       Zones
         should import records from a zone file:
     Error: Timeout of 2400000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/workspace/build/system-test/dns.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

That looks like the `done()` is not called in the async test. dns-zonefile doesn't have any async or promise operations. So I think I am pretty sure the problem is on the test code.

**Comment by elgs** [comment]
Somewhere in `should import records from a zone file` must have thrown any errors. Can you show me the content of this file?

```
/h/.npm/_logs/2021-07-08T15_29_12_112Z-debug.log
```

**Comment by elgs** [comment]
I have downloaded your code and linked my credit card to enable the billing account, and I am now able to test it. Give me some time and hopefully I can found what happened.

**Comment by elgs** [comment]
![image](https://user-images.githubusercontent.com/55955/127713303-ff2bd89b-aa43-4974-b2b0-41a9c75c99e6.png)

This line failed:
```ts
assert.strictEqual(
  spfRecord.toJSON().rrdatas![0],
  '"v=spf1" "mx:' + DNS_DOMAIN + '" "-all"'
);
```

I added this line:
```ts
console.log('expect', spfRecord.toJSON().rrdatas![0], 'to be', '"v=spf1" "mx:' + DNS_DOMAIN + '" "-all"');
```

and it prints:
```
expect "{data}" to be "v=spf1" "mx:gitnpm.com." "-all"
```

**Comment by elgs** [comment]
So looks like `{data}` not getting evaluated?

**Comment by elgs** [comment]
I downgraded to 0.2.6 and your tests passed. I will look into it.

**Comment by elgs** [comment]
Sorry it's my fault. Fixed in 0.2.8.

**Comment by bcoe** [comment]
@elgs thank you for helping us get to the bottom of this.

**Comment by sofisl** [comment]
Thank you @elgs!!
