### ISSUE TITLE
Flatten method regex matching with all the parenthesis and replace text on different indexes in updated text

### ISSUE THREAD

**Issue by imsiddhartha** [elgs/dns-zonefile#44]
Flatten method which is responsible for removing the parenthesis and change everything inside parenthesis to a single line instead of multiple lines e.g. 

```
@ 3600 IN SOA ns1-05.test-dns.com. abc-hostmaster.xyz.com (
1
3600
300
2419200
300
)

to 

@ 3600 IN SOA ns1-05.test-dns.com. abc-hostmaster.xyz.com ( 1 3600 300 2419200 300 )
```

But the problem is with regex it is using has 'g' (global) which means it will match all the lines which has parenthesis and then it is also replacing matched pattern with flattened text based on index and since after every update index of text would be different hence it will replace some other texts. Part of code which is responsible for this: https://github.com/elgs/dns-zonefile/blob/ec9f1cd9626f8e7e2811e489d71d0cb47bf79950/lib/zonefile.js#LL282C2-L285C4

Try running with following zone file:

```
$TTL 300
$ORIGIN exmaple.com

@ 3600 IN SOA ns1-05.test-dns.com. abc-hostmaster.xyz.com (
1
3600
300
2419200
300
)


long1024text	3600	IN	TXT	An MX (Mail Exchange) record is a type of DNS record used to specify the mail server responsible for accepting email messages for a domain. When someone sends an email message to an email address at a particular domain (such as example.com), their email c
long1024text	3600	IN	TXT	lient will query the DNS system for the MX record for that domain to determine which mail server to send the message to.
long1024text	3600	IN	TXT	The MX record typically contains a priority value and a hostname. The priority value indicates the order in which the mail servers should be contacted if there are multiple MX records for a given domain. The hostname specifies the domain name of the mail 
long1024text	3600	IN	TXT	server that should receive email messages for the domain.

```
## Here is the diff of the output
<img width="1187" alt="image" src="https://github.com/elgs/dns-zonefile/assets/15960830/646724fb-14a5-40a7-a9bf-c490d536f1aa">

**Comment by elgs** [comment]
Thank you @imsiddhartha. I will look into this issue.

**Comment by elgs** [comment]
I confirm this issue. Having a fix now. Thanks @imsiddhartha.

**Comment by elgs** [comment]
@imsiddhartha it should have been fixed in 0.3.1. Can you please have a try? Thanks.

**Comment by imsiddhartha** [comment]
Hey @elgs I saw your changes, the only thing I am concerned about is when there is no SOA record (not possible in RFC standard zone file but in some other cases it might possible) your code will throw in that case as it would be undefined.

I have done similar code change here: 
https://github.com/elgs/dns-zonefile/compare/master...imsiddhartha:dns-zonefile:dev/imsiddhartha/FlattenCorrection

**Comment by elgs** [comment]
So I guess it's safe to remove the SAO from the regular expression, assuming the first pair of parentheses will contain the SOA parameters, since any comments have been removed. Do you think that would work?

**Comment by elgs** [comment]
Sorry please ignore my last comment. I see what you meant.

**Comment by imsiddhartha** [comment]
Hmm created PR: https://github.com/elgs/dns-zonefile/pull/45 but will have conflicts now with your latest changes!

**Comment by elgs** [comment]
https://github.com/elgs/dns-zonefile/pull/46

Can I get your review?

**Comment by imsiddhartha** [comment]
Approved, thanks!
